domain: "sandersitkin.github.io"
url: "https://sandersitkin.github.io"
permalink: "/:categories/:year-:month-:day/:title"

title: "Sander Sitkin"
description: "Personal website of Sander Sitkin."

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

include:
  - "_pages"
